#!/usr/bin/env python3
"""Convert one generated Hexo/Fluid article back into a Hexo Markdown post.

Historical recovery utility. Specify a static-site snapshot and a separate
output directory explicitly. Normal editing and deployment use the recovered
sources directly and do not run this utility.
"""

from __future__ import annotations

import argparse
import html as html_lib
import json
import re
import shutil
from dataclasses import dataclass, field
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path
from typing import Iterable
from urllib.parse import quote, unquote, urlparse
from zoneinfo import ZoneInfo


VOID_TAGS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}

CUSTOM_PAGE_NAMES = (
    "ai",
    "ethics",
    "history",
    "military",
    "os",
    "quiz",
)

CUSTOM_ROOT_FILES = (
    "404.html",
)

# These are site-specific files used by the recovered standalone pages.  The
# normal Fluid assets are still generated by Hexo/theme, so we only copy the
# files that are not supplied by the test project's current theme.
CUSTOM_ASSETS = (
    "css/blog-polish.css",
    "img/favicon.png",
    "js/index-math.js",
    "js/quiz-ai.js",
    "js/tag-colors.js",
)

CUSTOM_ASSET_DIRS = (
    "files",
)

BLOCK_TAGS = {
    "blockquote",
    "div",
    "figure",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "ol",
    "p",
    "pre",
    "table",
    "ul",
}


@dataclass
class Node:
    tag: str | None
    attrs: dict[str, str] = field(default_factory=dict)
    children: list["Node | str"] = field(default_factory=list)


class DomParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self.root = Node(None)
        self.stack = [self.root]

    @property
    def current(self) -> Node:
        return self.stack[-1]

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        normalized = {key.lower(): value or "" for key, value in attrs}
        node = Node(tag.lower(), normalized)
        self.current.children.append(node)
        if tag.lower() not in VOID_TAGS:
            self.stack.append(node)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        normalized = {key.lower(): value or "" for key, value in attrs}
        self.current.children.append(Node(tag.lower(), normalized))

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        for index in range(len(self.stack) - 1, 0, -1):
            if self.stack[index].tag == tag:
                del self.stack[index:]
                return

    def handle_data(self, data: str) -> None:
        if data:
            self.current.children.append(data)

    def handle_entityref(self, name: str) -> None:
        self.current.children.append(html_lib.unescape(f"&{name};"))

    def handle_charref(self, name: str) -> None:
        self.current.children.append(html_lib.unescape(f"&#{name};"))

    def handle_comment(self, _data: str) -> None:
        return


def walk(node: Node) -> Iterable[Node]:
    for child in node.children:
        if isinstance(child, Node):
            yield child
            yield from walk(child)


def first_node(node: Node, predicate) -> Node | None:
    if predicate(node):
        return node
    for child in node.children:
        if isinstance(child, Node):
            found = first_node(child, predicate)
            if found is not None:
                return found
    return None


def classes(node: Node) -> set[str]:
    return set(node.attrs.get("class", "").split())


def raw_text(node: Node) -> str:
    chunks: list[str] = []
    for child in node.children:
        if isinstance(child, str):
            chunks.append(child)
        else:
            chunks.append(raw_text(child))
    return "".join(chunks)


def raw_code(node: Node) -> str:
    """Read code text while restoring line breaks represented by <br>."""
    chunks: list[str] = []
    for child in node.children:
        if isinstance(child, str):
            chunks.append(child)
        elif child.tag == "br":
            chunks.append("\n")
        else:
            chunks.append(raw_code(child))
    return "".join(chunks)


def protect_nunjucks_braces(formula: str) -> str:
    """Keep set notation from being mistaken for a Nunjucks expression."""
    return formula.replace("{{", "{&#123;").replace("}}", "}&#125;")


def protect_markdown_text(value: str) -> str:
    """Keep characters recovered from HTML text from becoming Markdown syntax."""
    return value.translate(str.maketrans({
        "*": "&#42;", "_": "&#95;", "~": "&#126;",
        "[": "&#91;", "]": "&#93;", "`": "&#96;",
        "<": "&#60;", ">": "&#62;",
    }))


def meta_values(root: Node, key: str) -> list[str]:
    values: list[str] = []
    for node in walk(root):
        if node.tag != "meta":
            continue
        if node.attrs.get("property") == key or node.attrs.get("name") == key:
            value = node.attrs.get("content", "").strip()
            if value:
                values.append(value)
    return values


def local_datetime(value: str) -> str:
    """Convert an ISO timestamp to the blog's Asia/Shanghai local time."""
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=ZoneInfo("Asia/Shanghai"))
        return parsed.astimezone(ZoneInfo("Asia/Shanghai")).strftime("%Y-%m-%d %H:%M:%S")
    except ValueError:
        return value


def yaml_string(value: str) -> str:
    # JSON double-quoted strings are valid YAML and preserve Chinese text.
    return json.dumps(value, ensure_ascii=False)


def fluid_config_from_html(html_source: str) -> dict | None:
    match = re.search(r"var\s+CONFIG\s*=\s*(\{.*?\});", html_source, flags=re.DOTALL)
    if match is None:
        return None
    try:
        value = json.loads(match.group(1))
    except json.JSONDecodeError:
        return None
    return value if isinstance(value, dict) else None


def category_paths(article: Node) -> list[list[str]]:
    paths: list[list[str]] = []
    for node in walk(article):
        if node.tag != "a":
            continue
        path = urlparse(node.attrs.get("href", "")).path
        marker = "/categories/"
        if marker not in path:
            continue
        suffix = path.split(marker, 1)[1]
        parts = [unquote(part) for part in suffix.split("/") if part]
        if parts and parts not in paths:
            paths.append(parts)

    if not paths:
        return []
    deepest = max(len(path) for path in paths)
    deepest_paths = [path for path in paths if len(path) == deepest]
    if deepest > 1:
        return [deepest_paths[0]]
    return paths


class MarkdownRenderer:
    def __init__(self, slug: str = "") -> None:
        self.slug = slug

    def inline_children(self, node: Node) -> str:
        return "".join(
            self.inline(child) if isinstance(child, Node) else self.text(child)
            for child in node.children
        )

    @staticmethod
    def text(value: str) -> str:
        # Hexo evaluates Nunjucks expressions before Markdown rendering.  A
        # recovered display formula such as `{{1,2}}` must therefore hide the
        # adjacent braces from that pass while leaving the browser-visible
        # formula unchanged after HTML entity decoding.
        return protect_markdown_text(protect_nunjucks_braces(re.sub(r"\s+", " ", value)))

    def inline(self, node: Node | str) -> str:
        if isinstance(node, str):
            return self.text(node)

        tag = node.tag or ""
        if tag in {"script", "math"} and node.attrs.get("type", "").startswith("math/tex"):
            formula = protect_markdown_text(protect_nunjucks_braces(raw_text(node).strip()))
            if "mode=display" in node.attrs.get("type", ""):
                dollars = chr(36) * 2
                return f"\n\n{dollars}\n{formula}\n{dollars}\n\n"
            return f"{chr(36)}{formula}{chr(36)}"

        if tag == "a" and "headerlink" in classes(node):
            return ""
        if tag == "br":
            return "  \n"
        if tag in {"strong", "b"}:
            content = self.inline_children(node).strip()
            # Keep the recovered emphasis as HTML.  Markdown's `**...**`
            # parsing is unreliable when the markers touch CJK text.
            return f"<strong>{content}</strong>" if content else ""
        if tag in {"em", "i"}:
            content = self.inline_children(node).strip()
            return f"<em>{content}</em>" if content else ""
        if tag in {"del", "s"}:
            content = self.inline_children(node).strip()
            return f"~~{content}~~" if content else ""
        if tag == "code":
            content = raw_text(node).strip().replace(chr(96), chr(92) + chr(96))
            return f"{chr(96)}{content}{chr(96)}" if content else ""
        if tag == "img":
            src = node.attrs.get("src", "").strip()
            alt = node.attrs.get("alt", "").strip()
            if src and not src.startswith(("/", "//", "http:", "https:", "data:")):
                src = f"/posts/{quote(self.slug)}/{src}"
            return f"![{alt}]({src})" if src else ""
        if tag == "a":
            content = self.inline_children(node).strip()
            href = node.attrs.get("href", "").strip()
            if not content:
                return ""
            if not href or href.startswith("javascript:"):
                return content
            return f"[{content}]({href})"
        if tag in BLOCK_TAGS:
            return self.block(node)
        if tag in {"style", "noscript"}:
            return ""
        return self.inline_children(node)

    def block(self, node: Node) -> str:
        tag = node.tag or ""

        if tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
            if node.attrs.get("id") == "seo-header":
                return ""
            content = self.inline_children(node).strip()
            return f"{'#' * int(tag[1])} {content}\n\n" if content else ""

        if tag == "p":
            content = self.inline_children(node).strip()
            return f"{content}\n\n" if content else ""

        if tag == "hr":
            return "---\n\n"

        if tag == "pre":
            code_node = first_node(node, lambda candidate: candidate.tag == "code")
            return self.fenced_code(code_node or node)

        if tag == "figure" and "highlight" in classes(node):
            code_node = first_node(node, lambda candidate: candidate.tag == "code")
            if code_node is not None:
                return self.fenced_code(code_node)
            pre = first_node(node, lambda candidate: candidate.tag == "pre")
            return self.block(pre) if pre is not None else ""

        if tag in {"ul", "ol"}:
            return self.list_block(node)

        if tag == "blockquote":
            content = self.container(node).strip()
            if not content:
                return ""
            return "\n".join(f"> {line}" if line else ">" for line in content.splitlines()) + "\n\n"

        if tag == "table":
            pre = first_node(node, lambda candidate: candidate.tag == "pre")
            if pre is not None:
                return self.block(pre)

        return self.container(node)

    def fenced_code(self, code_node: Node) -> str:
        code = raw_code(code_node).replace("\r\n", "\n").strip("\n")
        language = ""
        class_value = code_node.attrs.get("class", "")
        match = re.search(r"(?:language|lang)-([\w+-]+)", class_value)
        if match:
            language = match.group(1)
        elif "text" in class_value.split():
            language = "text"
        fence = chr(96) * 3
        return f"{fence}{language}\n{code}\n{fence}\n\n"

    def list_block(self, node: Node, indent: int = 0) -> str:
        ordered = node.tag == "ol"
        lines: list[str] = []
        number = 1
        for child in node.children:
            if not isinstance(child, Node) or child.tag != "li":
                continue

            main: list[str] = []
            nested: list[Node] = []
            for item in child.children:
                if isinstance(item, Node) and item.tag in {"ul", "ol"}:
                    nested.append(item)
                else:
                    main.append(self.inline(item) if isinstance(item, Node) else self.text(item))

            content = "".join(main).strip()
            prefix = f"{number}. " if ordered else "- "
            lines.append(" " * indent + prefix + content)
            number += 1

            for nested_list in nested:
                nested_text = self.list_block(nested_list, indent + 2).rstrip("\n")
                if nested_text:
                    lines.extend(nested_text.splitlines())

        return "\n".join(lines) + "\n\n" if lines else ""

    def container(self, node: Node) -> str:
        chunks: list[str] = []
        inline_buffer: list[str] = []

        def flush_inline() -> None:
            if not inline_buffer:
                return
            value = "".join(inline_buffer).strip()
            inline_buffer.clear()
            if value:
                chunks.append(value + "\n\n")

        for child in node.children:
            if isinstance(child, Node) and child.tag in BLOCK_TAGS:
                flush_inline()
                chunks.append(self.block(child))
            else:
                inline_buffer.append(self.inline(child) if isinstance(child, Node) else self.text(child))
        flush_inline()
        return "".join(chunks)

    def render(self, body: Node) -> str:
        rendered = self.container(body).replace("\r\n", "\n")
        rendered = re.sub(r"\n{3,}", "\n\n", rendered)
        rendered = re.sub(r"[ \t]+\n\n", "\n\n", rendered)
        return rendered.strip() + "\n"


def migrate_one(site_root: Path, output_root: Path, slug: str, copy_assets: bool, force: bool) -> Path:
    html_path = site_root / "posts" / slug / "index.html"
    if not html_path.is_file():
        raise FileNotFoundError(f"文章不存在: {html_path}")
    if site_root.resolve() == output_root.resolve():
        raise ValueError("输出目录不能是原博客目录")

    html_source = html_path.read_text(encoding="utf-8")
    parser = DomParser()
    parser.feed(html_source)
    article = first_node(parser.root, lambda node: node.tag == "article" and "post-content" in classes(node))
    if article is None:
        raise RuntimeError("没有找到 Fluid 文章容器 article.post-content")
    body = first_node(article, lambda node: node.tag == "div" and "markdown-body" in classes(node))
    if body is None:
        raise RuntimeError("没有找到 Fluid 文章正文 div.markdown-body")

    title = (meta_values(parser.root, "og:title") or [slug])[0]
    published = (meta_values(parser.root, "article:published_time") or [""])[0]
    modified = (meta_values(parser.root, "article:modified_time") or [""])[0]
    tags = meta_values(parser.root, "article:tag")
    categories = category_paths(article)
    renderer = MarkdownRenderer(slug)

    lines = ["---", f"title: {yaml_string(title)}"]
    if published:
        lines.append(f"date: {yaml_string(local_datetime(published))}")
    if modified:
        lines.append(f"updated: {yaml_string(local_datetime(modified))}")
    if categories:
        lines.append("categories:")
        for path in categories:
            if len(path) == 1:
                lines.append(f"  - {yaml_string(path[0])}")
            else:
                lines.append("  - [" + ", ".join(yaml_string(part) for part in path) + "]")
    if tags:
        lines.append("tags:")
        for tag in dict.fromkeys(tags):
            lines.append(f"  - {yaml_string(tag)}")
    lines.extend([f"permalink: {yaml_string(f'posts/{slug}/')}", "---", ""])
    markdown = "\n".join(lines) + renderer.render(body)
    if slug == "os-lab4-reflection":
        # The published post points to an unavailable external overview image.
        # The following three numbered steps contain the same essential flow.
        markdown = markdown.replace(
            "要求实现的功能如下图所示，你可以右键单击该图片，选择“在新标签页中打开”，以便于随时查看。\n\n"
            "![实现概览](https://os.buaa.edu.cn/public/23371058/extra/lab4-extra.png)\n\n"
            "具体地：",
            "要求实现的功能分为以下三个步骤：",
        )

    post_dir = output_root / "source" / "_posts"
    post_dir.mkdir(parents=True, exist_ok=True)
    output_file = post_dir / f"{slug}.md"
    if output_file.exists() and not force:
        raise FileExistsError(f"不会覆盖已有测试输出，请删除或改用 --force: {output_file}")
    output_file.write_text(markdown, encoding="utf-8", newline="\n")

    fluid_config = fluid_config_from_html(html_source)
    if fluid_config is not None:
        fluid_config_file = output_root / "_config.fluid.json"
        if fluid_config_file.exists() and not force:
            raise FileExistsError(
                f"不会覆盖已有测试配置，请删除或改用 --force: {fluid_config_file}"
            )
        fluid_config_file.write_text(
            json.dumps(fluid_config, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
            newline="\n",
        )

    asset_count = 0
    if copy_assets:
        source_asset_dir = site_root / "posts" / slug
        destination_asset_dir = post_dir / slug
        for asset in source_asset_dir.iterdir():
            if asset.name == "index.html" or not asset.is_file():
                continue
            destination_asset_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(asset, destination_asset_dir / asset.name)
            asset_count += 1

    print(f"source : {html_path}")
    print(f"output : {output_file}")
    print(f"title  : {title}")
    print(f"date   : {local_datetime(published) if published else '(missing)'}")
    print(f"tags   : {', '.join(tags) if tags else '(none)'}")
    print(f"assets : {asset_count} copied")
    print(f"fluid  : {'_config.fluid.json recovered' if fluid_config is not None else 'not found'}")
    return output_file


def copy_custom_pages(site_root: Path, output_root: Path, force: bool) -> tuple[int, int]:
    """Copy standalone non-Hexo app pages and their site-specific assets."""
    copied_pages = 0
    copied_assets = 0
    source_dir = output_root / "source"

    for name in CUSTOM_PAGE_NAMES:
        source_file = site_root / name / "index.html"
        if not source_file.is_file():
            continue
        output_file = source_dir / name / "index.html"
        if output_file.exists() and not force:
            raise FileExistsError(f"不会覆盖已有测试页面，请改用 --force: {output_file}")
        output_file.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_file, output_file)
        copied_pages += 1

    for name in CUSTOM_ROOT_FILES:
        source_file = site_root / name
        if not source_file.is_file():
            continue
        output_file = source_dir / name
        if output_file.exists() and not force:
            raise FileExistsError(f"不会覆盖已有测试页面，请改用 --force: {output_file}")
        output_file.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_file, output_file)
        copied_pages += 1

    for relative in CUSTOM_ASSETS:
        source_file = site_root / relative
        if not source_file.is_file():
            continue
        output_file = source_dir / relative
        if output_file.exists() and not force:
            raise FileExistsError(f"不会覆盖已有测试资源，请改用 --force: {output_file}")
        output_file.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_file, output_file)
        copied_assets += 1

    for relative_dir in CUSTOM_ASSET_DIRS:
        source_asset_dir = site_root / relative_dir
        if not source_asset_dir.is_dir():
            continue
        for source_file in source_asset_dir.rglob("*"):
            if not source_file.is_file():
                continue
            relative_file = source_file.relative_to(site_root)
            output_file = source_dir / relative_file
            if output_file.exists() and not force:
                raise FileExistsError(f"不会覆盖已有测试资源，请改用 --force: {output_file}")
            output_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_file, output_file)
            copied_assets += 1

    return copied_pages, copied_assets


def migrate_all(
    site_root: Path,
    output_root: Path,
    copy_assets: bool,
    force: bool,
    include_custom_pages: bool,
) -> None:
    """Recover every post plus the standalone pages from the static site."""
    posts_dir = site_root / "posts"
    post_dirs = sorted(
        (candidate for candidate in posts_dir.iterdir() if (candidate / "index.html").is_file()),
        key=lambda candidate: candidate.name,
    )
    if not post_dirs:
        raise FileNotFoundError(f"没有找到文章目录: {posts_dir}")

    migrated = 0
    for post_dir in post_dirs:
        migrate_one(site_root, output_root, post_dir.name, copy_assets, force)
        migrated += 1

    pages = assets = 0
    if include_custom_pages:
        pages, assets = copy_custom_pages(site_root, output_root, force)

    print(f"posts  : {migrated} migrated")
    print(f"pages  : {pages} standalone pages copied")
    print(f"assets : {assets} standalone assets copied")


def main() -> None:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site-root", type=Path, required=True, help="原静态站快照目录")
    parser.add_argument("--output-root", type=Path, required=True, help="单独的恢复输出目录")
    parser.add_argument("--slug", default="2026机器学习期末试题参考解答")
    parser.add_argument("--no-copy-assets", action="store_true")
    parser.add_argument("--force", action="store_true", help="允许覆盖测试目录中已有的输出文件")
    parser.add_argument(
        "--all",
        action="store_true",
        help="迁移原静态站中的全部文章和独立页面，而不是只迁移一篇文章",
    )
    parser.add_argument(
        "--no-custom-pages",
        action="store_true",
        help="使用 --all 时不复制刷题/AI 等独立页面",
    )
    args = parser.parse_args()
    site_root = args.site_root.resolve()
    output_root = args.output_root.resolve()
    if output_root == project_root:
        parser.error("恢复工具不能覆盖当前博客源码，请指定单独的 --output-root 目录")
    if site_root == output_root or site_root in output_root.parents or output_root in site_root.parents:
        parser.error("静态站快照与恢复输出目录不能互相包含")
    if args.all:
        migrate_all(
            site_root,
            output_root,
            not args.no_copy_assets,
            args.force,
            not args.no_custom_pages,
        )
    else:
        migrate_one(site_root, output_root, args.slug, not args.no_copy_assets, args.force)


if __name__ == "__main__":
    main()
