baseURL = "https://pppphop.github.io/"
languageCode = "zh-cn"
title = "pppphop的学习博客"
theme = "PaperMod"

[params]
  description = "分享专业课学习经验和知识总结"
  defaultTheme = "light"
  ShowBreadCrumbs = true
  ShowReadingTime = true
  # 启用数学公式支持
  math = true
  # 配置 Goldmark 以安全地渲染原始 HTML 和数学公式
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 注意：这允许渲染原始 HTML，请知悉
  # 配置数学公式渲染 (Hugo 0.123.0 及以上)
  [markup.math]
    enable = true
    # 默认渲染引擎是 'mathjax'，你也可以选择 'katex'
    # render = 'mathjax'
  
[params.assets]
  # 设置漂亮的背景图
  favicon = "/favicon.ico"
  # 你可以在这里添加自定义CSS
    customCSS = ["css/extended/custom.css"]
[menu]
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30

[params.homeInfoParams]
  Title = "欢迎来到我的学习博客"
  Content = """
  这里记录了我的专业课学习经验、技术总结和成长历程
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  preserveTaxonomyNames = true