baseURL = "https://pppphop.github.io/"
languageCode = "zh-cn"
title = "pppphop的学习博客"
theme = "PaperMod"

[params]
  description = "分享专业课学习经验和知识总结"
  defaultTheme = "auto"
  # 启用数学公式支持
  math = true
  customCSS = ["css/extended/custom.css"]
  
[params.assets]
  # 设置漂亮的背景图
  favicon = "/favicon.ico"
  # 你可以在这里添加自定义CSS

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30

[params.homeInfoParams]
  Title = "欢迎来到我的学习博客"
  Content = """
  这里记录了我的专业课学习经验、技术总结和成长历程
  """