baseURL = "https://pppphop.github.io/"
languageCode = "zh-cn"
title = "pppphop的学习博客"
theme = "PaperMod"

[params]
  description = "分享专业课学习经验和知识总结"
  defaultTheme = "auto"  # auto, light, dark
  # 启用主题颜色
  themeColor = "#3F51B5"
  # 启用主屏幕颜色
  maskColor = "#3F51B5"
  # 启用背景渐变
  #homeInfoParams = true
  # 启用社交图标
  socialIcons = true
  # 启用代码高亮
  highlightjs = true
  # 启用数学公式
  math = true
  # 自定义CSS
  customCSS = ["css/extended/custom.css"]

# 作者信息
[params.author]
  name = "pppphop"
  image = "/images/avatar.jpg"  # 你可以添加头像
  bio = "分享学习经验和技术总结"

# 社交链接
[params.social]
  GitHub = "pppphop"

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30

# 启用代码高亮
[markup.highlight]
  guessSyntax = true